name: dashboard_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - basemap=1.3.7
  - basemap-data=1.3.2
  - blas=1.0
  - bokeh=2.4.3
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.5.7
  - cartopy=0.21.1
  - certifi=2023.5.7
  - cf_xarray=0.8.1
  - cffi=1.15.1
  - cftime=1.6.2
  - charset-normalizer=3.1.0
  - cloudpickle=2.2.1
  - contourpy=1.0.5
  - cryptography=39.0.1
  - curl=7.88.1
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2023.4.1
  - dask-core=2023.4.1
  - dbus=1.13.18
  - distributed=2023.4.1
  - expat=2.4.9
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fsspec=2023.4.0
  - geos=3.11.2
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=7.88.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=12.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libllvm14=14.0.6
  - libnetcdf=4.8.1
  - libnghttp2=1.46.0
  - libpng=1.6.39
  - libpq=12.9
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzip=1.8.0
  - llvm-openmp=14.0.6
  - locket=1.0.0
  - lxml=4.9.2
  - lz4-c=1.9.4
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - msgpack-python=1.0.3
  - munkres=1.1.4
  - ncurses=6.4
  - netcdf4=1.6.2
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=1.1.1u
  - pandas=1.5.3
  - partd=1.2.0
  - pcre=8.45
  - pillow=9.4.0
  - pip=23.0.1
  - ply=3.11
  - pooch=1.7.0
  - proj=8.2.1
  - psutil=5.9.0
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyshp=2.1.3
  - pysocks=1.7.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - python-lmdb=1.4.1
  - python_abi=3.11
  - pytz=2022.7
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.31.0
  - setuptools=67.8.0
  - shapely=2.0.1
  - sip=6.6.2
  - six=1.16.0
  - sortedcontainers=2.4.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tblib=1.7.0
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.2
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=1.26.15
  - wheel=0.38.4
  - xarray=2022.11.0
  - xcdat=0.5.0
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zict=2.2.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - affine==2.4.0
    - ansi2html==1.8.0
    - anyio==3.7.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - async-lru==2.0.2
    - attrs==23.1.0
    - babel==2.12.1
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - bleach==6.0.0
    - cachelib==0.9.0
    - click==8.1.3
    - click-plugins==1.1.1
    - cligj==0.7.2
    - comm==0.1.3
    - dash==2.10.2
    - dash-core-components==2.0.0
    - dash-daq==0.5.0
    - dash-extensions==1.0.1
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - debugpy==1.6.7
    - decorator==5.1.1
    - defusedxml==0.7.1
    - editorconfig==0.12.3
    - executing==1.2.0
    - fastjsonschema==2.17.1
    - fiona==1.9.4.post1
    - flask==2.2.5
    - flask-caching==2.0.2
    - fqdn==1.5.1
    - geopandas==0.13.0
    - ipykernel==6.23.1
    - ipython==8.14.0
    - isoduration==20.11.0
    - itsdangerous==2.1.2
    - jedi==0.18.2
    - jsbeautifier==1.14.8
    - json5==0.9.14
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter-client==8.2.0
    - jupyter-dash==0.4.2
    - jupyter-events==0.6.3
    - jupyter-lsp==2.2.0
    - jupyter-server==2.6.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.0.1
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.22.1
    - llvmlite==0.40.0
    - markupsafe==2.1.2
    - matplotlib-inline==0.1.6
    - mistune==2.0.5
    - more-itertools==9.1.0
    - nbclient==0.8.0
    - nbconvert==7.4.0
    - nbformat==5.9.0
    - nest-asyncio==1.5.6
    - notebook-shim==0.2.3
    - numba==0.57.0
    - overrides==7.3.1
    - packaging==23.1
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - platformdirs==3.5.1
    - plotly==5.14.1
    - prometheus-client==0.17.0
    - prompt-toolkit==3.0.38
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyproj==3.5.0
    - pyrsistent==0.19.3
    - python-json-logger==2.0.7
    - pyzmq==25.1.0
    - rasterio==1.3.7
    - regionmask==0.10.0
    - retrying==1.3.4
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - scipy==1.10.1
    - send2trash==1.8.2
    - sniffio==1.3.0
    - snuggs==1.4.7
    - soupsieve==2.4.1
    - sparse==0.14.0
    - stack-data==0.6.2
    - tenacity==8.2.2
    - terminado==0.17.1
    - tinycss2==1.2.1
    - traitlets==5.9.0
    - uri-template==1.2.0
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.5.2
    - werkzeug==2.2.3
    - xesmf==0.7.1
